language: clojure
lein: 2.9.1
dist: focal
jobs:
  include:
    - stage: jdk8
      script: lein with-profile dev test
      jdk: openjdk8
    #- # same as previous stage
    #  script: lein with-profile fips test
    #  jdk: openjdk8
    - stage: jdk11
      script: lein with-profile dev test
      jdk: openjdk11
    #- # same as previous stage
    #  script: lein with-profile fips test
    #  jdk: openjdk11
sudo: false
# Java needs to be able to resolve its hostname when doing integration style
# tests, which it cannot do in certain cases with travis-ci.  If we need the
# runtime/container to be able to resolve its own hostname we need to use
# either the `hostname` or `hosts` "addon" for travis.  Since we don't care
# what the hostname is, here we just give it a garbage name based on the name
# of the project.
addons:
  hostname: cljhttpclient
notifications:
  email: false
